# Create numpy array using python "array like" data types

In [1]:
import numpy as np  # numpy is like a matrix unlike python

In [2]:
print(np.__version__)

1.20.1


In [3]:
my_list=[-17,0,4,5,9]

my_array_from_list=np.array(my_list) # .array() convert list to numpy array
my_array_from_list # feature of jupytor you don't need to use print but just the variable at the last to print it 

array([-17,   0,   4,   5,   9])

Elementry Multiplication

In [4]:
list_1=[1,2,3]
a=list_1*5
a

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [62]:
my_array_from_list*10# diff list is muliplied by 10 and not repeated 10 times like that happens in python

array([-170,    0,   40,   50,   90])

In [63]:
my_tuple=(14, -3.54, 5+7j)
np.array(my_tuple)

array([14.  +0.j, -3.54+0.j,  5.  +7.j])

# Difference between python and numpy data structure

In [64]:
my_tuple*5

(14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j))

np.array(my_tuple)*5

#  Intrinsic NumPy array creation using numpy's method

In [65]:
np.arange(7) # in python it is range here arange .arrange() shows the range from the starting point here 0

array([0, 1, 2, 3, 4, 5, 6])

In [66]:
np.arange(10,23)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [67]:
len(np.arange(10,23)) # length of the above 1-D array

13

In [68]:
my_range_array=np.arange(10,23)
my_range_array.size

13

In [69]:
np.arange(10,23,5) # here shows the range with stepsize 5

array([10, 15, 20])

In [5]:
np.arange(25, step=5)# just providing 5 won't be considered as a step size. So we need to specify the parameter name

array([ 0,  5, 10, 15, 20])

# numpy.matrix.transpose

In [6]:
a = np.array([[1, 2], [3, 4]]).T # .T for finding out the transpose
a
# consider matrix as a stack of lists

array([[1, 3],
       [2, 4]])

In [72]:
a.transpose() # square matrix for each row

array([[1, 2],
       [3, 4]])

# linspace(), zeros(), ones(), and NumPy data types

In [73]:
np.linspace(5,15,9, retstep=True)

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [74]:
my_linspace=np.linspace(0,360,10, retstep=True)
my_linspace
# a=np.arange(0,360,10)
# a

(array([  0.,  40.,  80., 120., 160., 200., 240., 280., 320., 360.]), 40.0)

In [9]:
#my_linspace=np.linspace(0,360, 10, retstep=True) # retstep shows the stepsize
#my_linspace
a=np.arange(0,360,10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290, 300, 310, 320, 330, 340, 350])

In [76]:
# print(a)
my_linspace

array([  0.,  40.,  80., 120., 160., 200., 240., 280., 320., 360.])

In [77]:
my_linspace[1]

40.0

# Zeros Function

In [78]:
np.zeros(5) # print aray will values of magnitude 5  '.' as the default data type is float
# dtype ='int32' change the data type from float to int ~> type casting

array([0., 0., 0., 0., 0.])

# Ones Function

In [79]:
 np.ones(5, dtype='int32') # thsi changes the default numpy float type to int

array([1, 1, 1, 1, 1], dtype=int32)

In [80]:
np.zeros((5,4)) # 2-D matrix with 5 rows and 4 columns  :- No of square brackets to know if it is 1-D or 2-D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [81]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((5,4,3)) # gives 3-D matrix [first parameter gives the no of matrix 5 2 dimensional matrix with dimensions 4 x 3]

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [91]:
np.zeros((2,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [83]:
np.zeros(5, dtype='int32')

array([0, 0, 0, 0, 0], dtype=int32)

In [84]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

# Slicing Array

In [11]:
my_vector=np.array([-17,-4,0,2,21,37,105])
(my_vector)

array([-17,  -4,   0,   2,  21,  37, 105])

In [86]:
my_vector[0] 

-17

In [14]:
my_vector[0]=-102
my_vector

array([-102,   -4,    0,    2,   21,   37,  105])

In [13]:
my_vector[-3] # element from the backward as it is negative

21

In [12]:
my_vector[105] # we are giving number and not index so we get an error

IndexError: index 105 is out of bounds for axis 0 with size 7

In [92]:
305%7

4

In [39]:
my_vector[305%7] # gives the result at the index 4

21

In [40]:
my_vector.size # .size gives the size of the array

7

In [41]:
my_vector[305%my_vector.size]

21

# Two Dimensional Array

In [96]:
# ~~~> BROADCASTING change the dimensions of an array ie; 1-D to 2-D and so on

# ~~~> 2-D array => list inside list combination of lists -matrix combination of matrix 3-D array
my_array=np.arange(1,36) # 1 D array from 1 to 36 - 1 = 35
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35])

In [97]:
my_array=np.arange(1,36).reshape(7,5) # 1-D to 2-D with same valid values ie; here 7 x 5 or 5 x 7
# my_array.shape=(7,5)
my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [49]:
my_array[2] # we will get the 1-D matrix at index 2 (consider matrix as a list inside a list)

array([11, 12, 13, 14, 15])

In [50]:
my_array[-2]

array([26, 27, 28, 29, 30])

In [52]:
my_array[5][2]

28

In [ ]:
row=5
column=2
my_array[row,column]

In [ ]:
my_array[5][2]

# Three Dimensional Array

In [56]:
my_3D_array=np.arange(70).reshape(2,7,5) # arange(70) created a matrix from 0 to 69
# my_3D_array.shape=(2,7,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [57]:
my_3D_array[1]

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [58]:
my_3D_array[1,3]

array([50, 51, 52, 53, 54])

In [59]:
my_3D_array[1,3,2]

52

In [60]:
my_3D_array[1,3,2]=1111
my_3D_array

array([[[   0,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14],
        [  15,   16,   17,   18,   19],
        [  20,   21,   22,   23,   24],
        [  25,   26,   27,   28,   29],
        [  30,   31,   32,   33,   34]],

       [[  35,   36,   37,   38,   39],
        [  40,   41,   42,   43,   44],
        [  45,   46,   47,   48,   49],
        [  50,   51, 1111,   53,   54],
        [  55,   56,   57,   58,   59],
        [  60,   61,   62,   63,   64],
        [  65,   66,   67,   68,   69]]])

In [ ]:
 import numpy as np

# Boolean Mask Array

In [61]:
my_vector=np.array([-17,-4,0,2,21,37,105])
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [16]:
zero_mode_7_mask=0 ==(my_vector%7) # divide by 7 if remainder 0 true otherwise false
zero_mode_7_mask

array([False, False,  True, False,  True, False,  True])

In [17]:
sub_array=my_vector[zero_mode_7_mask] # gives the values in the true indexes
sub_array

array([  0,  21, 105])

In [64]:
sub_array[sub_array>0]

array([ 21, 105])

In [ ]:
 sub_array

# NumPy Logical Operators

In [20]:
mod_test=0==(my_vector%7)
possitive_test=my_vector > 0
print(mod_test)
print(possitive_test)
combined_mask=np.logical_and(mod_test, possitive_test) # checks where both mod_test and possitive array has true
combined_mask

[False False  True False  True False  True]
[False False False  True  True  True  True]


array([False, False, False, False,  True, False,  True])

In [67]:
my_vector[combined_mask]

array([ 21, 105])

# Broadcasting : It defines that how numpy perform operations with an array of different sizes

In [68]:
my_3D_array=np.arange(70).reshape(2,7,5)
# my_3D_array.shape=(2,7,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [69]:
#.Shape shape of the matrix
my_3D_array.shape


(2, 7, 5)

In [70]:
#.ndim Number of dimensions
my_3D_array.ndim

3

In [71]:
# .Size size of the matrix
my_3D_array.size

70

In [72]:
#.dtype datatype for each elements
my_3D_array.dtype

dtype('int32')

In [73]:
5*my_3D_array-2

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [74]:
left_mat=np.arange(6).reshape((2,3))
print(left_mat)
right_mat=np.arange(6).reshape((3,2))
print(right_mat)
# multiplying two matrices  C1 = R2
# matrix multiplication is [[R1 x C1 ,R1 x C2],
#                          [R2 x C1 ,R2 x C2]h]

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [80]:
np.inner(left_mat.T, right_mat) # .inner() multiplication of matrices involving transpose

array([[ 3,  9, 15],
       [ 4, 14, 24],
       [ 5, 19, 33]])

In [78]:
np.dot(left_mat, right_mat)# .dot() matrix multiplication in numpy
# resultant will be having R1 x C2

array([[10, 13],
       [28, 40]])

# Operation along axis: Broadcasting along particular axis

In [81]:
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [82]:
my_3D_array.sum() # add all the numbers in the array

2415

In [83]:
my_2D_array=np.arange(15).reshape(3,5)
my_2D_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [84]:
my_2D_array.sum(axis=0) # addition vertically 

array([15, 18, 21, 24, 27])

In [85]:
my_2D_array.sum(axis=1) # horizontal addition of each rows (axis =1)

array([10, 35, 60])

In [ ]:
# my_3D_array.sum(axis=2)

# Broadcasting Rules

In [27]:
my_2D_array=np.ones(35, dtype="int").reshape(7,5)*3 # 0 to 34 ie; 35 values
my_2D_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [28]:
my_random_2D_array=np.random.randn(7,5) # .random() matrix with random values
my_random_2D_array

array([[-1.1707, -2.0484, -0.2156,  0.2307, -0.7619],
       [-0.1757,  0.9284, -0.343 , -0.8563, -0.7342],
       [-2.3125, -0.9555,  2.0429, -1.0389, -1.6388],
       [-0.6936, -1.0586, -0.034 ,  0.4905,  1.4567],
       [-0.2479, -0.6066,  1.076 ,  0.8238, -0.442 ],
       [-0.1153, -1.3255,  0.793 , -1.2557, -0.8359],
       [ 0.9957,  1.0612, -0.9416,  0.3452,  0.4641]])

In [29]:
np.set_printoptions(precision=4)
my_random_2D_array

array([[-1.1707, -2.0484, -0.2156,  0.2307, -0.7619],
       [-0.1757,  0.9284, -0.343 , -0.8563, -0.7342],
       [-2.3125, -0.9555,  2.0429, -1.0389, -1.6388],
       [-0.6936, -1.0586, -0.034 ,  0.4905,  1.4567],
       [-0.2479, -0.6066,  1.076 ,  0.8238, -0.442 ],
       [-0.1153, -1.3255,  0.793 , -1.2557, -0.8359],
       [ 0.9957,  1.0612, -0.9416,  0.3452,  0.4641]])

In [89]:
my_vector=np.arange(5)*7
my_vector[0]=-1
my_vector

array([-1,  7, 14, 21, 28])

In [32]:
my_2D_array*my_vector

ValueError: operands could not be broadcast together with shapes (7,5) (7,) 